### ISSUE TITLE
Help with NPE in Spring-Bundled Version of cglib

### ISSUE THREAD

**Issue by atorstling** [cglib/cglib#100]
Hello!

I have an issue with a large application utilizing IntelliJ's `@NotNull` annotation weaver (https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin)and spring core 4.2.6. Spring has a bundled version of cglib, which according to the sources should be cglib 3.1. I have however been unsuccessful when trying to correlate this stack trace with cglib 3.1. I am also unable to reproduce this error in small test cases, so I thought I would ask you for help. Can you make any sense of this stack trace?

```java

Caused by: java.lang.NullPointerException
	at java.lang.String.<init>(String.java:204)
	at org.springframework.asm.Type.getInternalName(Type.java:580)
	at org.springframework.cglib.core.CodeEmitter.emit_type(CodeEmitter.java:552)
	at org.springframework.cglib.core.CodeEmitter.checkcast(CodeEmitter.java:584)
	at org.springframework.cglib.proxy.Enhancer$6.emitInvoke(Enhancer.java:1128)
	at org.springframework.cglib.proxy.MethodInterceptorGenerator.superHelper(MethodInterceptorGenerator.java:143)
	at org.springframework.cglib.proxy.MethodInterceptorGenerator.generate(MethodInterceptorGenerator.java:103)
	at org.springframework.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1158)
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:581)
	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.aop.framework.CglibAopProxy$ClassLoaderAwareUndeclaredThrowableStrategy.generate(CglibAopProxy.java:990)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:312)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:445)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:85)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:83)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:105)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:278)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:433)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:338)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:55)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:203)
```

What I *can* conclude from this stacktrace is that `Type.getInternalName()` is called for the type boolean ('Z'), which isn't supported for primitive types according to the method documentation. The guard in `TypeEmitter.emit_type()` only checks for array types, and otherwise calls `getInternalName()`, which seems fishy.

While trying to modify the code slightly to see a pattern, I've also ran into issue #48 , so it seems likely that they are related. 

Thank you for your help.

**Comment by atorstling** [comment]
I managed to reproduce the error with a minimal test case: https://github.com/atorstling/cglib-spring-notnull-bug

**Comment by raphw** [comment]
I just ran your reproduction but I cannot reprocude the problem when running the test case. Are you sure that the problem is not on your end? Maybe your local repository is in a bad state?

**Comment by atorstling** [comment]
@raphw Thank you for looking into it. I can reproduce it at work and at home. I added a Dockerfile and a script - "run-in-docker.sh" to run it in an isolated environment and it manifests iself. Did you not get any exception at all?

This is the tail of what I get:

```
Caused by: java.lang.NullPointerException: null
	at java.lang.String.<init>(String.java:204)
	at org.springframework.asm.Type.getInternalName(Type.java:589)
	at org.springframework.cglib.core.CodeEmitter.emit_type(CodeEmitter.java:552)
	at org.springframework.cglib.core.CodeEmitter.checkcast(CodeEmitter.java:584)
	at org.springframework.cglib.proxy.Enhancer$6.emitInvoke(Enhancer.java:1185)
	at org.springframework.cglib.proxy.MethodInterceptorGenerator.superHelper(MethodInterceptorGenerator.java:143)
	at org.springframework.cglib.proxy.MethodInterceptorGenerator.generate(MethodInterceptorGenerator.java:103)
	at org.springframework.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1215)
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:630)
	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.aop.framework.CglibAopProxy$ClassLoaderAwareUndeclaredThrowableStrategy.generate(CglibAopProxy.java:991)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:55)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:203)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
	at org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.postProcessAfterInitialization(AbstractAdvisingBeanPostProcessor.java:90)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  ApplicationTests.contextLoads » IllegalState Failed to load ApplicationContext

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.527 s
[INFO] Finished at: 2017-04-07T12:01:51+00:00
[INFO] Final Memory: 28M/198M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project cglib-spring-notnull-bug: There are test failures.
[ERROR] 
[ERROR] Please refer to /target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c mvn install' returned a non-zero code: 1
```

**Comment by raphw** [comment]
This seems to be a problem in the `BridgeMethodResolver` which incorrectly identifies the constructor to be a bridge of the `update` method. As a result, cglib attempts to *cast* the `boolean` return value to `void` what is of course non-sense.

The bridge method finder seems to rely on the visitation order of a class, i.e. that the bridge is visited subsequently to the original method. That is of course non-sense but I would neither know how to fix it. This code is ancient and was probably smacked in after the relase of generics in Java 5.

**Comment by atorstling** [comment]
@raphw : Thank you for your analysis and comments. I concluded that synthetic methods were being instrumented, and that is probably what is confusing the `BridgeMethodResolver`. I did a PR for it at https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin/pull/17 , and now with `intellij-annotations-instrumenter-maven-plugin` `0.6.6`, the synthetic methods shouldn't be instrumented anymore and this bug won't be triggered.

I also concluded that this bug report is a duplicate of #48 , if you change the code in `UserRepo.java` trivially (change return type from `boolean` to `Boolean`) you get the same stack trace as in #48 .

**Comment by atorstling** [comment]
I also found this related issue: https://github.com/jqno/equalsverifier/issues/115

**Comment by raphw** [comment]
Thanks for following up. I will see if I can fix this bug somehow but I do not think this is possible without major changes to cglib which I am scared to do.
