### ISSUE TITLE
IllegalArgumentException in BridgeMethodResolver using JDK 9

### ISSUE THREAD

**Issue by melix** [cglib/cglib#106]
Hi team,

We're trying to upgrade the Gradle build to make it run on JDK 9, and we're facing issues with our tests that use mocking. Some of them are failing with the following exception:

```
Caused by: java.lang.IllegalArgumentException
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:63)
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1132)
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:630)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:91)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:83)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at ReproSpec.should not throw IllegalArgumentException(ReproSpec.groovy:6)
```

The reproduction instructions can be found in this repository: https://github.com/melix/repro-cglib-bug-jdk9

Let me know if I can help.

**Comment by raphw** [comment]
You can use Spock with Byte Buddy which has better support for Java 9 than cglib can offer. But I will of course look into this.

**Comment by melix** [comment]
Do you mean replacing the dependency from `cglib-nodep` to `bytebuddy` should be enough?

**Comment by raphw** [comment]
Yes, that [should do the trick](https://github.com/spockframework/spock/blob/5157299cb5aac34d2070ed5aac10a449b06156ab/spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java#L55).

Beware that Byte Buddy's mock classes are slightly different (retain generic types and other meta data).

**Comment by raphw** [comment]
The problem is cglib's way of detecting bridge methods which requires reading the class file and parsing it for bridges. Class files should always be visible, even outside of a module; that is strange so to speak. I will investigate.

**Comment by melix** [comment]
mmm, looks like using ByteBuddy doesn't help. After updating the dependencies in the repro sample to:

```
dependencies {
    testCompile 'org.codehaus.groovy:groovy:2.4.11'
    testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
    testCompile 'net.bytebuddy:byte-buddy:1.7.1'
}
```

I get:

```
Caused by: org.spockframework.mock.CannotCreateMockException: Cannot create mock for class java.io.File. Mocking of non-interface types requires the CGLIB library. Please put cglib-nodep-2.2 or higher on the class path.
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:52)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:83)
```

**Comment by raphw** [comment]
Support for Byte Buddy was added in Spock 1.1. Can you update?

**Comment by melix** [comment]
Ah right. I think I cannot upgrade so easily, using Spock 1.1 introduced other failures :(

**Comment by raphw** [comment]
I will try to fix cglib to resolve the class file from the module but that is really not trivial so it might take a bit.

**Comment by melix** [comment]
No worries, thanks for investigating!

**Comment by raphw** [comment]
My bad, the problem is that cglib is still using ASM 5.2 whereas ASM 6 is not yet released. You should be able to use cglib (with dependencies and add ASM 6.ALPHA manually to make things work.

**Comment by melix** [comment]
@raphw I could confirm that the [build passes](https://scans.gradle.com/s/y74gaqgogdntq/dependencies?dependencies=cglib&focusedDependency=WzEsMiw1NTMsWzAsMCxbMF1dXQ%3D%3D&search) after updating to `cglib` and adding ASM 6 alpha as a dependency (remaining failures are not related to this issue).

However I'm a bit reluctant to adding an ALPHA dependency to Gradle. @forax any ETA for a final release? I know you were waiting for migration to Git, but it seems that quite a few projects are waiting for ASM6 to be released...

**Comment by raphw** [comment]
I have asked for ASM 6 before but it does not seem like there will be a release before Java 9 is released. I wait for this myself to push all users upstream...

**Comment by forax** [comment]
Expect a beta next week end :)

As Raphael said, the full release is coordinated with the Java release (as for ASM 4 & 5).

**Comment by raphw** [comment]
@forax Great, thank you. By the way: why not migrate ASM over to GitHub? Would make it much easier to contribute!

**Comment by forax** [comment]
We are close to announce that we have migrated to git (issues are not yet migrated)
  https://gitlab.ow2.org/asm/asm

It's not on github but i'm sure there is a way to mirror the source from gitlab to github
(i've just checked, it's a feature of gitlab EE but OW2 is using the community edition :( )

**Comment by raphw** [comment]
@forax: are there plans to publisg ASM 6.BETA to Maven Central?

**Comment by don-vip** [comment]
It seems done now: http://repo1.maven.org/maven2/org/ow2/asm/asm/6.0_BETA/

**Comment by stefanneuhaus** [comment]
I observed the same issue. Compiling the sources to target version 1.8 fixed it in my case. This could also be a workaround if it is feasible for you.
