### ISSUE TITLE
Does not support lombok @Accessors(chain = true)

### ISSUE THREAD

**Issue by yeaicc** [cglib/cglib#108]
`BeanCopier.create` will throw exception when the `source` or `target` use `@Accessors(chain = true)` in lombok.
But `org.springframework.beans.BeanUtils.copyProperties(source, target);` has no problem.
```java
java.lang.NullPointerException
	at net.sf.cglib.core.ReflectUtils.getMethodInfo(ReflectUtils.java:424)
	at net.sf.cglib.beans.BeanCopier$Generator.generateClass(BeanCopier.java:133)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at net.sf.cglib.beans.BeanCopier$Generator.create(BeanCopier.java:90)
	at net.sf.cglib.beans.BeanCopier.create(BeanCopier.java:50)
```

**Comment by wangxi761** [comment]
Did you solve it?

**Comment by yeaicc** [comment]
use `org.springframework.beans.BeanUtils.copyProperties(source, target);`

**Comment by friends110110** [comment]
But org.springframework.beans.BeanUtils.copyProperties(source, target); is another solution, so if still use cglib, how to do ?

**Comment by yangcoolq** [comment]
BeanCopier是基于ASM字节码增强做的，效率比Spring的要高很多 （仅次于硬编码）。不建议因为这个原因去用Spring或者apache的BeanUtils。还是老老实实用@Builder吧

**Comment by tanyaofei** [comment]
use [BeanCopier](https://github.com/tanyaofei/beancopier)

**Comment by lolli-alex** [comment]
> use [BeanCopier](https://github.com/tanyaofei/beancopier)
java.lang.NoSuchMethodError: sun.misc.Unsafe.defineClass(Ljava/lang/String;[BIILjava/lang/ClassLoader;Ljava/security/ProtectionDomain;)Ljava/lang/Class;
	at io.github.tanyaofei.beancopier.ConverterFactory.generateConverter(ConverterFactory.java:189) ~[beancopier-0.1.5.jar:na]
	at io.github.tanyaofei.beancopier.BeanCopierImpl.lambda$generateConverter$3(BeanCopierImpl.java:436) ~[beancopier-0.1.5.jar:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
	at io.github.tanyaofei.beancopier.BeanCopierImpl.generateConverter(BeanCopierImpl.java:434) ~[beancopier-0.1.5.jar:na]
	at io.github.tanyaofei.beancopier.BeanCopierImpl.copy(BeanCopierImpl.java:215) ~[beancopier-0.1.5.jar:na]
	at io.github.tanyaofei.beancopier.BeanCopier.copy(BeanCopier.java:47) ~[beancopier-0.1.5.jar:na]
@tanyaofei
