### ISSUE TITLE
Help debugging 

### ISSUE THREAD

**Issue by joel-costigliola** [cglib/cglib#116]
Hi,

I'm struggling debugging this issue https://github.com/joel-costigliola/assertj-core/issues/1146.
Is there a way to find out which is the duplicate method mentioned in the exception ?

```
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.assertj.core.internal.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459)
at org.assertj.core.internal.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
... 39 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file org/assertj/core/api/ObjectArrayAssert$$EnhancerByCGLIB$$2a693b8d$$EnhancerByCGLIB$$e518c7e6
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
```
Thanks in advance

**Comment by raphw** [comment]
I checked and the problem is cglib proxying another cglib proxied class:

org.assertj.core.api.ObjectArrayAssert$$EnhancerByCGLIB$$30eb9e74$$EnhancerByCGLIB$$ffbccd53 extends org.assertj.core.api.ObjectArrayAssert$$EnhancerByCGLIB$$30eb9e74.

This causes a duplicate registration of the callback cglib-internal methods whose names are not randomized.

**Comment by joel-costigliola** [comment]
thanks @raphw! 
would byte buddy be able such a case ?

**Comment by joel-costigliola** [comment]
It seems byte-buddy handles that case correctly :smile_cat:

**Comment by raphw** [comment]
Byte Buddy is based on a different model then cglib. Byte Buddy adds none of its own types into proxy classes to avoid this problem but also solve issues like OSGi (and now Java 9 module) boundary violations. This is why this should not be an issue there.
