### ISSUE TITLE
Dead lock when new thread started in static block

### ISSUE THREAD

**Issue by yanxinyuan** [cglib/cglib#123]
Dears,
    I'm not sure if this is a bug or some guideline need to comply with. I use cglib to generate dynamic proxy of my own class named "DoOne", in the class I start a new thread in its static block. I got a dead lock in the thread when it use its classLoader to load a class.

Here is my code.
```
                String className = "com.cglib.xy.sample.DoOne";
		File testJar = new File("./lib/test.jar");
		if (!testJar.exists()) throw new FileNotFoundException();
		
		UserClassLoader loader = new UserClassLoader(new URL[]{testJar.toURI().toURL()}, LuchMain.class.getClassLoader());
		Class<?> loadClass = loader.loadClass(className);
		
		MethodInterceptor interceptor = new MethodInterceptor() {
			@Override
			public Object intercept(Object obj, Method method, Object[] args, MethodProxy proxy) throws Throwable {
				return proxy.invokeSuper(obj, args);
			}
		};
		Callback[] callbacks = new Callback[] { interceptor, NoOp.INSTANCE };
		Enhancer enhancer = new Enhancer();
		enhancer.setSuperclass(loadClass);
		enhancer.setCallbackFilter(new CallbackFilter() {
			@Override
			public int accept(Method arg0) {
				return 0;
			}
		});
		enhancer.setCallbacks(callbacks);
		enhancer.setClassLoader(loader);
		Object obj = enhancer.create();
		System.out.println(obj);

```

```
public class DoOne {

	static {
		init();
	}
  
	public void complete() {
		System.out.println("Do One.");
	}
	
	public static void init() {
		System.out.println("start init");
		
		Thread t1 = new Thread(new Runnable() {
	        @Override
	        public void run() {
	        	try {
	        		System.out.println("thread in");
				DoOne.class.getClassLoader().loadClass("com.cglib.for.fun"); // dead lock
				System.out.println("thread out");
				} catch (ClassNotFoundException e) {
					e.printStackTrace();
				}
	        }
	    }, "Test-1");
	    
		try {
			t1.start();
			t1.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		System.out.println("end init");
	}
}

```
more code please refer to [https://github.com/yanxinyuan/cglib-deadlock](url)

**Comment by yanxinyuan** [comment]
After i use jstack command to verify its status, i got this, it seems there are two place to competitive one monitor lock.

```
"Test-1" #14 prio=5 os_prio=0 tid=0x000000001948e000 nid=0x36f0 waiting for monitor entry [0x000000001b7bf000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.cglib.xy.sample.DoOne$1.run(DoOne.java:20)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
"main" #1 prio=5 os_prio=0 tid=0x0000000002eb2800 nid=0x1a28 in Object.wait() [0x0000000002eae000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d6467270> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x00000000d6467270> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1319)
	at com.cglib.xy.sample.DoOne.init(DoOne.java:29)
	at com.cglib.xy.sample.DoOne.<clinit>(DoOne.java:6)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:415)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	- locked <0x00000000d6117800> (a com.cglib.xy.sample.UserClassLoader)
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:305)
	at com.cglib.xy.sample.LuchMain.main(LuchMain.java:47)

   Locked ownable synchronizers:
	- None

```

**Comment by yanxinyuan** [comment]
I go through the code and i found this two places may have exclusion.

```
abstract public class AbstractClassGenerator<T>
implements ClassGenerator {
...
protected Class generate(ClassLoaderData data) {
...
 synchronized (classLoader) { // just in case ,<- this line
                if (protectionDomain == null) {
                    gen = ReflectUtils.defineClass(className, b, classLoader);
                } else {
                    gen = ReflectUtils.defineClass(className, b, classLoader, protectionDomain); 
                }
            }
            return gen;
}
```

```
public abstract class ClassLoader {
...
    protected Class<?> loadClass(String name, boolean resolve)
        throws ClassNotFoundException
    {
        synchronized (getClassLoadingLock(name)) { // <- this line
       Class<?> c = findLoadedClass(name);
...
```

**Comment by vlsi** [comment]
I believe this duplicates https://github.com/cglib/cglib/issues/120

**Comment by yanxinyuan** [comment]
Yes, it seems related but i'm not sure they are the same reasons.
