### ISSUE TITLE
can not support android

### ISSUE THREAD

**Issue by zhangjunapk** [cglib/cglib#145]
I just wanna generate proxy class on android with cglib ,but it response this exception 

Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:345)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
        at org.zj.core.util.DynamicProxyUtil.generateProxyObjectEdittext(DynamicProxyUtil.java:30) 
        at org.zj.core.Zygote.setBindEditText(Zygote.java:85) 
        at org.zj.core.Zygote.initValueBind(Zygote.java:78) 
        at org.zj.core.Zygote.init(Zygote.java:50) 
        at org.zj.MainActivity.onCreate(MainActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:6807) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2735) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2843) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6285) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459)
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:452)
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:334)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) 
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) 
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) 
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) 
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153) 
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) 
        at org.zj.core.util.DynamicProxyUtil.generateProxyObjectEdittext(DynamicProxyUtil.java:30) 
        at org.zj.core.Zygote.setBindEditText(Zygote.java:85) 
        at org.zj.core.Zygote.initValueBind(Zygote.java:78) 
        at org.zj.core.Zygote.init(Zygote.java:50) 
        at org.zj.MainActivity.onCreate(MainActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:6807) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2735) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2843) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6285) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829) 
     Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
        at java.lang.ClassLoader.defineClass(ClassLoader.java:594)
        at java.lang.reflect.Method.invoke(Native Method) 
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459) 
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:452) 
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:334) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) 
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) 
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) 
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) 
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153) 
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) 
        at org.zj.core.util.DynamicProxyUtil.generateProxyObjectEdittext(DynamicProxyUtil.java:30) 
        at org.zj.core.Zygote.setBindEditText(Zygote.java:85) 
        at org.zj.core.Zygote.initValueBind(Zygote.java:78) 
        at org.zj.core.Zygote.init(Zygote.java:50) 
        at org.zj.MainActivity.onCreate(MainActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:6807) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2735) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2843) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6285) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

**Comment by raphw** [comment]
Android defines a custom byte code format. Cglib cannot work on that platform. Have a look at Byte Buddy and its Android class loading strategy which might work for you.

**Comment by zhangjunapk** [comment]
good idea , I will try it
