### ISSUE TITLE
Java 16 compatibility

### ISSUE THREAD

**Issue by robertandrewbain** [cglib/cglib#191]
Upgrading to Java 16 I receive the following Exception. I tried adding the VM option `--add-opens java.base/java.lang=ALL-UNNAMED` which I thought would work around the issue to no avail.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.example.main(Example.java:10)
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @39aeed2f
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
	... 1 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @39aeed2f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at net.sf.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at net.sf.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52)
	at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
	... 13 more
```

**Comment by raphw** [comment]
Did you place cglib in a module? This is supposed to solve your problem. Alternatively, you can change the setting that forbids accessing internal API.

**Comment by robertandrewbain** [comment]
cglib is a transitive dependency so I can't put it in a module. As I mentioned above, `--add-opens java.base/java.lang=ALL-UNNAMED` doesn't appear to work. Minimal reproducible example using Java 16:

```
import net.sf.cglib.proxy.Enhancer;

public class Main {
    public static void main(String[] args) {
        new Enhancer();
    }
}
```

**Comment by wind57** [comment]
@raphw can you please explain what you mean by _you can change the setting that forbids accessing internal API._? thank you

**Comment by namannigam** [comment]
@wind57 This has been discussed and an **alternate** approach for users unless `cglib` upgrades is suggested [here](https://stackoverflow.com/a/67006749/1746118), i.e to make use of the override `--illegal-access=permit`.

**Comment by cowwoc** [comment]
I believe the correct fix for this problem would be for cglib to ship with a `module-info.java` that imports `java.base`. You can use multi-release JARs to maintain support for older JDKs. Example: https://www.baeldung.com/maven-multi-release-jars

**Comment by nmandrescu** [comment]
[JEP 403](https://openjdk.java.net/jeps/403) targeted for JDK 17 (release planned for [Sept 2021](https://openjdk.java.net/projects/jdk/17/)) will remove `--illegal-access` flag. That will be equivalent to `--illegal-access=deny`.

cglib can go with [standard replacements](https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool#JavaDependencyAnalysisTool-ReplaceusesoftheJDK'sinternalAPIs) for the most commonly used internal elements of the JDK.

**Comment by rototor** [comment]
FYI: I've just implemented an initial hacky workaround to make cglib some kind of work with JDK17.  See this commit https://github.com/rototor/cglib/commit/cc8632ed0930879b929b0d07e4ede5ac15103e9f 

It's ugly because it needs to get a class in the package of the class going to be defined. To do so it does some "magic" with the class path, including (in my case) stripping "Wicket_Proxy_" prefixes.

Feel free to use this as a base to make a clean version of it. (The real solution for me would be if Wicket just migrated to ByteBuddy...)

**Comment by robertandrewbain** [comment]
Is there likely to be a Java 17 compatibility fix in the near future? I know Apache Wicket are affected by this and looking at putting in a fix but if a fix is planned at this end, they don't need to worry. https://issues.apache.org/jira/browse/WICKET-6913

**Comment by JJBRT** [comment]
It can be solved **without any JVM parameter** with [**Burningwave Core reflection components**](https://github.com/burningwave/core#Handling-privates-and-all-other-members-of-an-object)  that thanks to a [special driver](https://burningwave.github.io/jvm-driver/) work on all JDKs [from 8](https://dev.to/jjbrt/how-to-make-reflection-fully-work-on-jdk-16-and-later-ihp). In this case you can also simply call the method `org.burningwave.core.assembler.StaticComponentContainer.Modules.exportAllToAll()`

**Comment by cowwoc** [comment]
Instead of layering one hack on top of another, wouldn't it be better to implement this using public methods that are guaranteed to continue working in the future?

**Comment by JJBRT** [comment]
At runtime is not possible at the moment without hacks, but if you are interested here you can find a complete example of [how to export all modules to all modules at runtime in Java 16 and later](https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m)

**Comment by adityajoshee** [comment]
Any update for the fix for java 17?

**Comment by cowwoc** [comment]
Last commit to this project is August 2019. Methinks it's time to bury it.

**Comment by rototor** [comment]
@adityajoshee  I don't think that there will be a fixed release for JDK 17. If at any way possible you should migrate to [ByteBuddy](https://bytebuddy.net/). If you have CGLib as dependency of some other library you use, you should try to migrate to the latest version of this library. E.g. Wicket and Hibernate already migrated away to ByteBuddy.

As a last resort you can use my commit https://github.com/rototor/cglib/commit/cc8632ed0930879b929b0d07e4ede5ac15103e9f as a base for your own local built and deployed cglib version.

**Comment by sameb** [comment]
FYI all, I added a note to the top-level README about its current state: 

***IMPORTANT NOTE: cglib is unmaintained and does not work well (or possibly at all?) in newer JDKs, particularly JDK17+. If you need to support newer JDKs, we will accept well-tested well-thought-out patches... but you'll probably have better luck migrating to something like ByteBuddy.***

**Comment by DanielThomas** [comment]
For those unable to migrate to ByteBuddy easily, Spring Framework maintains patches for cglib that include compatibility for Java 17, you could do a similar thing and embed cglib into your sources:

https://github.com/spring-projects/spring-framework/tree/main/spring-core/src/main/java/org/springframework/cglib

**Comment by buttercannfly** [comment]
try add jvm option
` - JVM_OPTS=  --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED
`

**Comment by shuodashen** [comment]
> For those unable to migrate to ByteBuddy easily, Spring Framework maintains patches for cglib that include compatibility for Java 17, you could do a similar thing and embed cglib into your sources:
> 
> https://github.com/spring-projects/spring-framework/tree/main/spring-core/src/main/java/org/springframework/cglib

I have replace cglib to the one embeded in spring framework, but the issue still occurs:

 org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @385e9564
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:598) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[spring-core-5.3.23.jar:5.3.23]

**Comment by JJBRT** [comment]
It can be solved **without any JVM parameter** with [**Burningwave Core reflection components**](https://github.com/burningwave/core#Handling-privates-and-all-other-members-of-an-object)  that thanks to a [special driver](https://burningwave.github.io/jvm-driver/) work on all JDKs [from 8](https://dev.to/jjbrt/how-to-make-reflection-fully-work-on-jdk-16-and-later-ihp). In this case you can also simply call the method `org.burningwave.core.assembler.StaticComponentContainer.Modules.exportAllToAll()`

**Comment by KouShenhai** [comment]
> try add jvm option `- JVM_OPTS= --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED`

Problem solved，thank you very much

**Comment by ilwsm** [comment]
> > try add jvm option `- JVM_OPTS= --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED`
> 
> Problem solved，thank you very much

How did is in Idea?

**Comment by Garlic6694** [comment]
just use spring-core cglib,do not need to change code:

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>

import org.springframework.cglib.proxy.Enhancer;

**Comment by KamakshaiahM** [comment]
> > try add jvm option `- JVM_OPTS= --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED`
> 
> Problem solved，thank you very much

Hi - Can you please where and how did you added thee options? I am using maven, spring boot latest versions, while migrating to jdk 17 i am getting  InaccessibleObjectException, please advise. Thanks,

**Comment by KouShenhai** [comment]
> > > 尝试添加 JVM 选项`- JVM_OPTS= --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED`
> > 
> > 
> > 问题解决了，非常感谢
> 
> 嗨 - 您能否请问您在哪里以及如何添加这些 jvm 选项？我正在使用 maven，Spring 启动最新版本，在迁移到 jdk 17 时，我遇到了无法访问的对象异常，请告知。谢谢

--add-opens=java.base/java.security=ALL-UNNAMED

**Comment by KamakshaiahM** [comment]
> > For those unable to migrate to ByteBuddy easily, Spring Framework maintains patches for cglib that include compatibility for Java 17, you could do a similar thing and embed cglib into your sources:
> > https://github.com/spring-projects/spring-framework/tree/main/spring-core/src/main/java/org/springframework/cglib
> 
> I have replace cglib to the one embeded in spring framework, but the issue still occurs:
> 
> org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @385e9564 at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:598) ~[spring-core-5.3.23.jar:5.3.23] at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363) ~[spring-core-5.3.23.jar:5.3.23] at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110) ~[spring-core-5.3.23.jar:5.3.23] at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[spring-core-5.3.23.jar:5.3.23]

Hi, did you get this working? Please advise how did you solved this issue?

**Comment by isMrZhang** [comment]
I seem to have found the answer, it works fine on spring-core-6.0.15 and the key to the fix lies in this patch.
![image](https://github.com/cglib/cglib/assets/54580227/a38f94de-009b-44c6-88c1-f3e5c55ea008)
 spring-projects/spring-framework#28699

**Comment by devjohnpark** [comment]
![Screenshot 2024-08-23 at 9 27 20 PM](https://github.com/user-attachments/assets/182b0f3c-bc06-496f-8993-a4a2b87e8653)

IntelliJ top bar -> Run -> Edit Configurations -> Modify options -> Add VM options -> Add the below option.

`--add-opens java.base/java.lang=ALL-UNNAMED`

Add the above JVM option to your classes that use CGLIB. This should basically unlock reflection access on certain paths.


This error is caused by the module system introduced in Java 9 and later. It indicates that CGLIB tried to access the `defineClass` method of Java's `ClassLoader` class, but this method is not accessible.

Specifically, Java's module system restricts reflection access to certain packages or classes by default, and `InaccessibleObjectException` can be raised when a library such as CGLIB tries to access a restricted method.

It need to make reflection access unrestricted by default on certain paths. Therefore, add the following JVM option.

**Comment by Mubir** [comment]
> - JVM_OPTS= --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED

not working at all

**Comment by arysin** [comment]
> try add jvm option `- JVM_OPTS= --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED`

This worked for me, thanks!
