### ISSUE TITLE
Support Java 8

### ISSUE THREAD

**Issue by pniederw** [cglib/cglib#8]
cglib 3.1 doesn't seem to work under Java 8. In the best case, all that's required is to update to ASM 5 (see https://github.com/cglib/cglib/issues/7).

**Comment by jayjupdhig** [comment]
I just try to instantiate the "Enhancer" class in a Java 8 Eclipse project and then i get an exception:

Code:

```
	public PreviousActivityImplementer generateCGLIBProxyInstanceFor(Class<PreviousActivityImplementer> superClazz) {

		Enhancer enhancer = new Enhancer();
		// enhancer.setSuperclass(superClazz);
		
		/*
		enhancer.setCallback(new MethodInterceptor() {
			public Object intercept(Object arg0, Method arg1, Object[] arg2, MethodProxy arg3) throws Throwable {
				String name = arg1.getName();
				if ("bar".equals(name)) {
					System.out.println("bar");
				}
				return null;
			}
		});
*/
		
		// return superClazz.cast(enhancer.create());
		
		return null;
	}
```


Exception:

```
test1 ... 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at cglibExample.CgLibTest.generateCGLIBProxyInstanceFor(CgLibTest.java:36)
	at cglibExample.Main.test1(Main.java:17)
	at cglibExample.Main.<init>(Main.java:8)
	at cglibExample.Main.main(Main.java:29)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49)
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
	... 4 more

```


With that code, the exception is gone:

```
public PreviousActivityImplementer generateCGLIBProxyInstanceFor(Class<PreviousActivityImplementer> superClazz) {

		// Enhancer enhancer = new Enhancer();
		// enhancer.setSuperclass(superClazz);
		
		/*
		enhancer.setCallback(new MethodInterceptor() {
			public Object intercept(Object arg0, Method arg1, Object[] arg2, MethodProxy arg3) throws Throwable {
				String name = arg1.getName();
				if ("bar".equals(name)) {
					System.out.println("bar");
				}
				return null;
			}
		});
*/
		
		// return superClazz.cast(enhancer.create());
		
		return null;
	}
```


So full proof that the cause is the "Enhancer" class!!

Used versions:

- `asm-5.2.jar`
- `cglib-3.3.0.jar`


Why? How to solve that problem?

So please don't hesitate to ask me if you need closer informations.

Thank you very much for your feedback.


With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
- Change constructor visibility from "private" to "public" does also not help.

- Change class visibility from the inner static class does also not help:

```
public static abstract class PreviousActivityImplementer {

		public abstract Class<?> setPreviousActivity(final Object caActivity);
	}
```

**Comment by jayjupdhig** [comment]
On current version download, i read:

```
"emits code compatible with java 1.8, so we can call static interface methods."
```

???

**Comment by jayjupdhig** [comment]
https://repo1.maven.org/maven2/cglib/cglib-nodep/3.2.4/cglib-nodep-3.2.4.jar has solved the problem ...

So the combinations of "asm-5.2.jar" and "cglib-3.3.0.jar" is NOT Java 8 compatible, that's just simply wrong!!

So both producers of that libraries tell that their versions are java 8 compatible (asm on version 5.2, cglib on 3.3.0) - which is a lie...
